# Generated by Django 4.2.30 on 2026-04-17 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('license_photo_url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Processing', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
