# Generated by Django 4.2.30 on 2026-04-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_trustrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trustrequest',
            name='license_photo_url',
        ),
        migrations.AddField(
            model_name='trustrequest',
            name='license_photo',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
    ]
