# Generated by Django 4.2.30 on 2026-04-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_rental_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='engine_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='geofence_radius',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='rental',
            name='last_lat',
            field=models.FloatField(default=25.1972),
        ),
        migrations.AddField(
            model_name='rental',
            name='last_lng',
            field=models.FloatField(default=55.2744),
        ),
    ]
