# Generated by Django 4.2.30 on 2026-04-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Hatchback', 'Hatchback'), ('Pickup', 'Pickup'), ('Van', 'Van')], default='Sedan', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='category_tier',
            field=models.CharField(choices=[('Luxury', 'Luxury'), ('Performance', 'Performance'), ('Economy', 'Economy'), ('Classic', 'Classic')], default='Luxury', max_length=50),
        ),
    ]
