# Generated by Django 4.2.30 on 2026-04-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='image_url',
        ),
        migrations.AddField(
            model_name='part',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='car_make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parts/'),
        ),
        migrations.AddField(
            model_name='part',
            name='is_accessory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='model_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
