# Generated by Django 4.2.30 on 2026-04-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_part_image_url_part_brand_part_car_make_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='installation_available',
            field=models.BooleanField(default=False),
        ),
    ]
