# Generated by Django 4.2.30 on 2026-04-20 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_alter_appointment_status_alter_workorder_status'),
        ('store', '0003_part_installation_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='workshop_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_orders', to='workshop.appointment'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='workshop_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Prepared', 'Prepared'), ('Out_For_Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Ready_For_Installation', 'Ready for Installation'), ('Delivered_With_Installation', 'Delivered with Installation'), ('Delivered_Only', 'Delivered Only')], default='Pending', max_length=30),
        ),
    ]
