# Generated by Django 4.2.30 on 2026-04-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_conciergemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conciergemessage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='conciergemessage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
