# Generated by Django 4.2.30 on 2026-04-19 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='workshop_category',
            field=models.CharField(choices=[('Polishing_Ceramic', 'Full Polishing and Ceramic Workshop'), ('Diagnostic_Inspection', 'Diagnostic Inspection Workshop'), ('Maintenance_Accessories', 'Maintenance and Accessories Installation Workshop')], default='Maintenance_Accessories', max_length=50),
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('working_days', models.CharField(max_length=100)),
                ('working_hours', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Polishing_Ceramic', 'Full Polishing and Ceramic Workshop'), ('Diagnostic_Inspection', 'Diagnostic Inspection Workshop'), ('Maintenance_Accessories', 'Maintenance and Accessories Installation Workshop')], max_length=50)),
                ('service_location_type', models.CharField(choices=[('Internal', 'Internal Only'), ('Mobile', 'Mobile Only'), ('Both', 'Internal & Mobile')], default='Both', max_length=50)),
                ('manager', models.OneToOneField(blank=True, limit_choices_to={'role': 'WorkshopManager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_workshop', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='workorder',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='workshop.workshop'),
        ),
    ]
