# Generated by Django 4.2.30 on 2026-04-19 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_part_installation_available'),
        ('workshop', '0004_appointment_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='additional_parts_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Maintenance_Done', 'Maintenance Done (Pending Payment)'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='workshop.worker'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('Unassigned', 'Unassigned'), ('In_Progress', 'In Progress'), ('Awaiting_Payment', 'Awaiting Payment'), ('Completed', 'Completed')], default='Unassigned', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkOrderPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.part')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='workshop.workorder')),
            ],
        ),
    ]
