# Generated by Django 4.2.30 on 2026-04-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_workorder_additional_parts_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='unforeseen_costs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
