# Generated by Django 4.2.30 on 2026-04-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_workorder_unforeseen_costs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Maintenance_Done', 'Maintenance Done (Pending Payment)'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('Unassigned', 'Unassigned'), ('In_Progress', 'In Progress'), ('Awaiting_Payment', 'Awaiting Payment'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Unassigned', max_length=20),
        ),
    ]
